var giga={ready:function(fn){if(document.attachEvent?document.readyState==='complete':document.readyState!=='loading')
{fn()}
else{document.addEventListener('DOMContentLoaded',fn)}},showTool:function(){for(var i=0;i<5;i++)
{if(document.querySelectorAll('div.gigacalculator')[i]==undefined)return;var tool=document.querySelectorAll('div.gigacalculator')[i].getAttribute('data-tool');var width=document.querySelectorAll('div.gigacalculator')[i].getAttribute('data-width');if(tool.indexOf('?')>0){tool=tool+'&'}else{tool=tool+'?'}
document.querySelectorAll('div.gigacalculator')[i].style='width: '+width+'px;';document.querySelectorAll('div.gigacalctitle')[i].style='font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol"; font-size: 1.3rem; color: #1b6997 !important; text-align: center; background-color: #f6f6f6; border-radius: 0.25rem; padding-top: 0.75rem; padding-bottom: 1rem; margin-bottom: -0.25rem;';document.querySelectorAll('div.gigacalcfooter')[i].style='font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol"; font-size: 0.9rem; color: #1b6997 !important; text-align: center; background-color: #f6f6f6; border-radius: 0.25rem; padding-top: 1rem; padding-bottom: 0.75rem; margin-top: -0.25rem; display: block !important;';document.querySelectorAll('div.gigacalcfooter>a')[i].style='text-decoration: none; font-size: 12px !important; color: #1b6997 !important;';document.querySelectorAll('a.gigacalclink')[i].style='text-decoration: none; color: #1b6997 !important;';document.querySelectorAll('a.gigacalclink')[i].innerHTML='<img src="" style="vertical-align: middle; display: inline; box-shadow: none;" alt="" />';document.querySelectorAll('div.gigacalctitle')[i].insertAdjacentHTML('afterend','<iframe id="gigaframe" src="https://www.gigacalculator.com'+tool+'embed=true" style="display: block; border: none; width: 100%; margin: 0px; padding: 0px; height: 240px; visibility: visible; opacity: 1;"></iframe>')}},resizeIframe:function(){iframe=document.getElementById('gigaframe');iframe.style.height=giga.iframeHeight+"px"}};giga.iframeHeight=240;window.addEventListener('message',function(event){if(~event.origin.indexOf('https://www.gigacalculator.com')){giga.iframeHeight=event.data;giga.resizeIframe()}else{return}});giga.ready(giga.showTool);giga.clearResultHooks=function(){calcRes=document.getElementById('calcResult');if(calcRes!=undefined)
{calcResDis=document.getElementById('calcResult').style.display}
else{return}
Array.prototype.forEach.call(document.querySelectorAll('form#calculator input'),function(el,i)
{el.addEventListener('keyup',function()
{if(calcResDis!='none')calcRes.style.display='none'});el.addEventListener('change',function()
{if(calcResDis!='none')calcRes.style.display='none'})});Array.prototype.forEach.call(document.querySelectorAll('form#calculator select'),function(el,i)
{el.addEventListener('change',function()
{if(calcResDis!='none')calcRes.style.display='none'})});Array.prototype.forEach.call(document.querySelectorAll('form#calculator radio'),function(el,i)
{el.addEventListener('change',function()
{if(calcResDis!='none')calcRes.style.display='none'})})};giga.ready(giga.clearResultHooks)
